### ISSUE TITLE
Implementar camara para que mande video

### ISSUE THREAD

**Issue by gayoso** [BigFiuBrother/big-fiubrother-camera#3]
Permitir mandar video a traves de rabbitmq

**Comment by eduardoneira** [comment]
Se puede mandar video por rabbitmq. Los videos por lo que vi pesan entre 500KB y 800KB con una resolución de 1080p. Voy a bajarla a 720p porque no me parece necesario aunque 1 mensaje de ese peso por segundo no es tanto.
